export const SET_GIVEN_OFFERS = "SET_GIVEN_OFFERS";
export const SET_RECEIVED_OFFERS = "SET_RECEIVED_OFFERS";

//saga
export const SG_FETCH_GIVEN_OFFERS = "SG_FETCH_GIVEN_OFFERS";
export const SG_CANCEL_OFFER = "SG_CANCEL_OFFER";
export const SG_ACCEPT_OFFER = "SG_ACCEPT_OFFER";
export const SG_REJECT_OFFER = "SG_REJECT_OFFER";
export const SG_FETCH_RECEIVED_OFFERS = "SG_FETCH_RECEIVED_OFFERS";
