export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";
export const SET_CATEGORIES = "SET_CATEGORIES";

//saga
export const SG_FETCH_PRODUCTS = "SG_FETCH_PRODUCTS";
export const SG_FETCH_CATEGORIES = "SG_FETCH_CATEGORIES";
export const SG_FETCH_PRODUCT_DETAIL = "SG_FETCH_PRODUCT_DETAIL";
export const SG_GIVE_OFFER = "SG_GIVE_OFFER";
