export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_DETAILS = "SET_PRODUCT_DETAILS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_NEW_IMAGE_URL = "SET_NEW_IMAGE_URL";

//saga
export const SG_FETCH_PRODUCTS = "SG_FETCH_PRODUCTS";
export const SG_FETCH_CATEGORIES = "SG_FETCH_CATEGORIES";
export const SG_FETCH_PRODUCT_DETAIL = "SG_FETCH_PRODUCT_DETAIL";
export const SG_GIVE_OFFER = "SG_GIVE_OFFER";
export const SG_CREATE_PRODUCT = "SG_CREATE_PRODUCT";
export const SG_UPLOAD_NEW_PRODUCT_IMAGE = "SG_UPLOAD_NEW_PRODUCT_IMAGE";
